name: DadBodIssue
version: '${project.version}'
main: com.wipdev.dadbodissue.DadBodIssue
api-version: '1.20'
commands :
  sethome:
    description: Sets a home/Overrides existing home
    usage: /sethome <name> [public/private]
    aliases: [sh]
  delhome:
    description: Deletes a home
    usage: /delhome <name>
    aliases: [dh]
  home:
    description: Warps to a home
    usage: /home <name>
    aliases: [h]

